[package]
name = "advent_of_code_2015"
version = "0.1.0"
authors = ["jasonbrackman <brackman@gmail.com>"]

[dependencies]
md5 = "0.6.0"
regex = "1.0.0"
permutohedron = "0.2.4"
serde = "1.0.80"
serde_json = "1.0.33"